[build]
  command = "npm run build --prefix frontend"  # Command to build your project
  publish = "frontend/dist"                     # Directory containing the built files

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200